include:
  - remote: 'https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/ed640900/templates/fedora.yml'

stages:
  - container
  - test

variables:
  FDO_UPSTREAM_REPO: malureau/rdw
  GIT_SUBMODULE_STRATEGY: recursive

.rdw.fedora:37:
  variables:
    FDO_DISTRIBUTION_VERSION: 37
    FDO_DISTRIBUTION_TAG: '2022-11-15.0'

build-fedora-container:
  extends:
  - .fdo.container-build@fedora@x86_64
  - .rdw.fedora:37
  stage: container
  variables:
    FDO_DISTRIBUTION_PACKAGES: >-
      cargo
      freerdp-devel
      git
      gobject-introspection-devel
      gstreamer1-devel
      gstreamer1-plugins-base-devel
      gtk4-devel
      gvnc-devel
      openssl-devel
      rust
      spice-glib-devel
      usbredir-devel
      vala
    FDO_DISTRIBUTION_EXEC: >-
      cargo install cargo-c

test-build:
  extends:
    - .fdo.distribution-image@fedora
    - .rdw.fedora:37
  stage: test
  script:
    - pushd rdw4
    - gtk4-broadwayd :0 &
    - GDK_BACKEND=broadway BROADWAY_DISPLAY=:0 make
    - sudo make install
    - popd
    - cargo build
