[package]
name = "demo"
version = "0.1.0"
authors = ["Marc-André Lureau <marcandre.lureau@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = { version = "0.7", default-features = false }
gtk = { package = "gtk4", git = "https://github.com/gtk-rs/gtk4-rs" }
rdw-vnc = { path = "../rdw-vnc" }
